version: '3.8'

services:
  port-tariff-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    volumes:
      # Mount logs directory to persist logs
      - ./logs:/app/logs
      # Mount for development (optional - uncomment for development)
      # - ./api.py:/app/api.py
      # - ./tariff_engine:/app/tariff_engine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 30s 